name: Build and deploy Python app to Azure Web App - WebAppTest2406

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Package artifact for deployment
        run: | 
          tar -czvf output.tar.gz --exclude='venv' --exclude='.git' --exclude='output.tar.gz' . 

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: output.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: tar -xzvf output.tar.gz -C ${{runner.temp}}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C205BF8BB7774381BF547043171A05ED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6FBD5CF1C53F4B7CBCFEB73E053110EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3A537D2533684193B531B997DD67D606 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'WebAppTest2406'
          slot-name: 'Production'
          package: ${{runner.temp}} 